import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { Story } from '../components/_About/Story/Story';
import { CoreTeam } from '../components/CoreTeam/CoreTeam';
import { BannerAbout } from '../components/Banner/Banner';
import { Layout } from '../components/Layout/Layout';

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Private Studio - About</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Story />
        <CoreTeam />
        <BannerAbout />
      </Layout>
    </>
  );
};

export default About;
