import {NextPage} from 'next';
import Head from 'next/head';
import React from 'react';
import {Layout} from '../components/Layout/Layout';

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Private Studio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <h1>About Page</h1>
      </Layout>
    </>
  );
};

export default About;
