import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { Layout } from '../components/Layout/Layout';
import { ContactPage } from '../components/Contact/Contact';

const Contact: NextPage = () => {
  return (
    <>
      <Head>
        <title>Private Studio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <ContactPage />
      </Layout>
    </>
  );
};

export default Contact;
