import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { ErrorSection } from '../components/ComponentError/ErrorSection/ErrorSection';
import { Layout } from '../components/Layout/Layout';

const Error: NextPage = () => {
  return (
    <>
      <Head>
        <title>Private Studio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <ErrorSection />
      </Layout>
    </>
  );
};

export default Error;
