import type { NextPage } from 'next';
import Head from 'next/head';
import { Service } from '../components/Home/Service/Service';
import { Banner } from '../components/Banner/Banner';
import { OurCustomer } from '../components/OurCustomer/OurCustomer';
import { KeyMessage } from '../components/Global/KeyMessage/KeyMessage';
import { OurWork } from '../components/Home/OurWork/OurWork';
import { Layout } from '../components/Global/Layout/Layout';
import { Approach } from '../components/Approach/Approach';
import { Careers } from '../components/Home/Careers/Careers';
import styled, { keyframes } from 'styled-components';
import { bounceInUp } from 'react-animations';
import { useEffect } from 'react';

const bounceAnimation = keyframes`${bounceInUp}`;

const BouncyDiv = styled.div`
  animation: 2s ${bounceAnimation};
`;

const BounceInUpDiv = styled.div`
  animation: 1s ${bounceAnimation};
`;

const Home: NextPage = () => {
  2;
  useEffect(() => {
    const inViewport = (entries: any, observer: any) => {
      entries.forEach((entry: any) => {
        if (entry.isIntersecting) {
          entry.target.classList.add('active', entry.isIntersecting);
        }
      });
    };

    const Obs = new IntersectionObserver(inViewport);

    // Attach observer to every [data-inviewport] element:
    const ELs_inViewport = document.querySelectorAll('[data-inviewport]');
    ELs_inViewport.forEach((EL) => {
      Obs.observe(EL);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Private Studio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Banner />
        <BouncyDiv>
          <KeyMessage type={true} />
        </BouncyDiv>
        <div className='load-lazy' data-inviewport>
          <div className='service'>
            <BounceInUpDiv>
              <Service />
            </BounceInUpDiv>
          </div>
        </div>
        <div className='load-lazy' data-inviewport>
          <div className='our-work'>
            <BounceInUpDiv>
              <OurWork />
            </BounceInUpDiv>
          </div>
        </div>
        <div className='load-lazy' data-inviewport>
          <div className='our-customer'>
            <BounceInUpDiv>
              <OurCustomer />
            </BounceInUpDiv>
          </div>
        </div>
        <div className='load-lazy' data-inviewport>
          <div className='approach'>
            <BounceInUpDiv>
              <Approach />
            </BounceInUpDiv>
          </div>
        </div>
        <div className='load-lazy' data-inviewport>
          <div className='career'>
            <BounceInUpDiv>
              <Careers />
            </BounceInUpDiv>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Home;
