import type {NextPage} from "next";
import Head from "next/head";
import {ClientSays} from "../components/ClientSays/ClientSays";
// import Image from "next/image";
import {Layout} from "../components/Layout/Layout";
import {KeyMessage} from "../components/KeyMessage/KeyMessage";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ClientSays />
        <KeyMessage />
      </Layout>
    </>
  );
};

export default Home;
