import type {NextPage} from "next";
import Head from "next/head";
// import Image from "next/image";
import {Layout} from "../components/Layout/Layout";
import {SectionTitle} from "../components/SectionTitle/SectionTitle";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SectionTitle />
      </Layout>
    </>
  );
};

export default Home;
