import {NextPage} from 'next';
import Head from 'next/head';
import React from 'react';
import {WorkingProcess} from '../components/WorkingProcess/WorkingProcess';
import {WorkBanner} from '../components/_Work/WorkBanner/WorkBanner';
import {OurWork} from '../components/Work/OurWork/OurWork';
import {Layout} from '../components/Global/Layout/Layout';

const Work: NextPage = () => {
  return (
    <>
      <Head>
        <title>Private Studio - Working</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <WorkBanner />
        <OurWork />
        <WorkingProcess />
      </Layout>
    </>
  );
};

export default Work;
