import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { WorkingProcess } from "../components/WorkingProcess/WorkingProcess";
import { Banner } from "../components/Banner/Banner";
import { Layout } from "../components/Layout/Layout";

const Work: NextPage = () => {
  return (
    <>
      <Head>
        <title>Private Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Work Page</h1>
        <WorkingProcess />
        <Banner
          Banner={true}
          SubTitle="A diversity of expertise to solve challenges in a unique way with creative courage"
        />
      </Layout>
    </>
  );
};

export default Work;
